---
  - name: "Installation de l'environnement"
    hosts: localhost
    vars_prompt:
    - name: ssh_email
      prompt: What is your SSH email?
      private: false
    tasks:
    

#####################  INSTALLATION CURL  #####################
    - name: Install Curl
      become: yes
      apt:
        name: curl
        
#####################  INSTALLATION SIGNAL  #####################
    - name: Install Signal
      become: yes
      community.general.flatpak:
        name: org.signal.Signal
        state: present
      
      
#####################  INSTALLATION VSCODE  #####################
    - name: Install Visual Studio Code
      community.general.flatpak:
        name: com.visualstudio.code
        state: present

#####################  INSTALLATION KEEPASS  #####################
    - name: Check if 'keepass2' is installed
      command: dpkg-query -l keepass2
      register: deb_check_keepass
      ignore_errors: yes
    - name: Install Keepass
      become: yes
      shell: "./playbook_scripts/install_keepass.sh"
      when: deb_check_keepass.stdout.find('no packages found') != -1
    - name: Download latest Keepass plugins
      become: yes
      shell: "./playbook_scripts/get_latest_keepass_plugin.sh"

#####################  INSTALLATION OBSIDIAN  #####################
    - name: Install Obsidian
      become: yes
      community.general.flatpak:
        name: md.obsidian.Obsidian
        state: present

#####################  INSTALLATION GPARTED  #####################
    - name: Install Gparted
      become: yes
      apt:
        name: gparted

#####################  INSTALLATION LIBRE OFFICE  #####################
    - name: Install Libre Office
      become: yes
      community.general.flatpak:
        name: org.libreoffice.LibreOffice
        state: present

#####################  INSTALLATION Discord  #####################
    - name: Install Discord
      become: yes
      community.general.flatpak:
        name: com.discordapp.Discord
        state: present

#####################  INSTALLATION vlc  #####################
    - name: Install vlc
      become: yes
      apt:
        name: vlc
        
#####################  INSTALLATION Nextcloud  #####################
    - name: Install Nextcloud
      become: yes
      community.general.flatpak:
        name: com.nextcloud.desktopclient.nextcloud
        state: present
        
#####################  COPIE SCRIPTS  #####################
    - name: Copy upgrade script
      copy:
        src: "./resources/upgrade"
        dest: "~/.local/bin/upgrade"
        mode: "555"
        
#####################  INSTALLATION GIT  #####################
    - name: Install Git
      become: yes
      apt:
        name: git-all
    - name: Default editor
      git_config:
        name: core.editor
        scope: global
        value: code
    - name: Pull rebase
      git_config:
        name: pull.rebase
        scope: global
        value: true
#####################  INSTALLATION SSH  #####################
    - name: Generate ssh PERSO
      community.crypto.openssh_keypair:
        path: ~/.ssh/id_rsa_perso
        comment: "{{ssh_email}}"
        type: rsa
        size: 4096
    - name: Copy files from several directories
      copy:
        src: "./resources/ssh_config"
        dest: "~/.ssh/config"

#####################  INSTALLATION SDKMAN  #####################
    - name: Check if SDKMAN is installed
      command: sdk version
      register: sdkman_valid
      ignore_errors: yes
    - name: Install SDKMAN
      shell: "./playbook_scripts/install_sdkman.sh"
      when: sdkman_valid.failed
#####################  INSTALLATION NVM  #####################
    - name: Check if NVM is installed
      command: nvm --version
      register: nvm_valid
      ignore_errors: yes
    - name: Install NVM
      shell: "./playbook_scripts/install_nvm.sh"
      when: nvm_valid
#####################  INSTALLATION DOCKER  #####################
    - name: Check if 'docker' is installed
      command: docker --version
      register: docker_valid
      ignore_errors: yes
    - name: Install Docker
      become: yes
      shell: "./playbook_scripts/install_docker.sh"
      when: docker_valid.failed

#####################  INSTALLATION INTELLIJ  #####################
    - name: Install IntelliJ
      become: yes
      community.general.flatpak:
        name: com.jetbrains.IntelliJ-IDEA-Ultimate
        state: present


#####################  INSTALLATION REMMINA  #####################
    - name: Install Remmina
      become: yes
      community.general.flatpak:
        name: org.remmina.Remmina
        state: present

#####################  INSTALLATION POSTMAN  #####################
    - name: Install Bruno
      become: yes
      community.general.flatpak:
        name: com.usebruno.Bruno
        state: present
        
