---
  - name: "Installation de l'environnement"
    hosts: localhost
    vars_prompt:
    - name: ssh_email
      prompt: What is your SSH email?
      private: false
    tasks:


#################################################
#####################  DEV  #####################
#################################################

#####################  COPIE SCRIPTS  #####################
    - name: Copy upgrade script
      become: yes
      copy:
        src: "./resources/upgrade"
        dest: "/usr/local/bin/upgrade"
        mode: "555"

#####################  INSTALLATION VSCODE  #####################
    - name: Install Visual Studio Code
      community.general.flatpak:
        name: com.visualstudio.code
        state: present

#####################  INSTALLATION GIT  #####################
    - name: Install Git
      become: yes
      apt:
        name: git-all
    - name: Default editor
      git_config:
        name: core.editor
        scope: global
        value: code
    - name: Pull rebase
      git_config:
        name: pull.rebase
        scope: global
        value: true

#####################  INSTALLATION INTELLIJ  #####################
    - name: Install IntelliJ
      become: yes
      snap:
        name: intellij-idea-ultimate
        classic: yes
        state: present

#####################  INSTALLATION REMMINA  #####################
    - name: Install Remmina
      become: yes
      community.general.flatpak:
        name: org.remmina.Remmina
        state: present

#####################  INSTALLATION POSTMAN  #####################
    - name: Install Bruno
      become: yes
      community.general.flatpak:
        name: com.usebruno.Bruno
        state: present

#####################  INSTALLATION SSH  #####################
    - name: Generate ssh PERSO
      community.crypto.openssh_keypair:
        path: ~/.ssh/id_rsa_perso
        comment: "{{ssh_email}}"
        type: rsa
        size: 4096
    - name: Copy files from several directories
      copy:
        src: "./resources/ssh_config"
        dest: "~/.ssh/config"

#####################  INSTALLATION SDKMAN  #####################
    - name: Install SDKMAN
      shell: "./playbook_scripts/install_sdkman.sh"

#####################  INSTALLATION NVM  #####################
    - name: Install NVM
      shell: "./playbook_scripts/install_nvm.sh"

#####################  INSTALLATION PODMAN  #####################
    - name: Install Podman
      become: yes
      apt:
        name: podman


#################################################
#####################  PERSO  #####################
#################################################

#####################  INSTALLATION SIGNAL  #####################
    - name: Install Signal
      become: yes
      community.general.flatpak:
        name: org.signal.Signal
        state: present
      
#####################  INSTALLATION GPARTED  #####################
    - name: Install Gparted
      become: yes
      apt:
        name: gparted

#####################  INSTALLATION KEEPASS  #####################
    - name: Check if 'keepass2' is installed
      command: dpkg-query -l keepass2
      register: deb_check_keepass
      ignore_errors: yes
    - name: Install Keepass
      become: yes
      shell: "./playbook_scripts/install_keepass.sh"
      when: deb_check_keepass.stdout.find('no packages found') != -1
    - name: Download latest Keepass plugins
      become: yes
      shell: "./playbook_scripts/get_latest_keepass_plugin.sh"

#####################  INSTALLATION LIBRE OFFICE  #####################
    - name: Install Libre Office
      become: yes
      community.general.flatpak:
        name: org.libreoffice.LibreOffice
        state: present

#####################  INSTALLATION Discord  #####################
    - name: Install Discord
      become: yes
      community.general.flatpak:
        name: com.discordapp.Discord
        state: present

#####################  INSTALLATION vlc  #####################
    - name: Install vlc
      become: yes
      apt:
        name: vlc
        
#####################  INSTALLATION Nextcloud  #####################
    - name: Install Nextcloud
      become: yes
      community.general.flatpak:
        name: com.nextcloud.desktopclient.nextcloud
        state: present